--==============NOT NULL CONTRAINTS ============

--[1] ADD CONSTRAINTS WHEN TABLE IS CREATE

DROP TABLE TEMP;
CREATE TABLE TEMP (
    ID NUMBER(2) CONSTRAINTS temp_id_nn NOT NULL,
    NAME VARCHAR2(20) CONSTRAINTS temp_name_nn NOT NULL,
    CITY VARCHAR2(20)
);

--[2] ADD CONSTRAINTS WHEN TABLE IS AFTER CREATE TABLE

ALTER TABLE TEMP
    MODIFY CITY NOT NULL;

--[3] REMOVE OR DEROP CONSTRAINTS

ALTER TABLE TEMP 
	DROP CONSTRAINTS temp_name_nn;

ALTER TABLE TEMP
	MODIFY CITY NULL;

DESC TEMP;


--==============UNIQUE CONSTRAINTS ============

--[1] ADD CONSTRAINTS WHEN TABLE IS CREATE

DROP TABLE TEMP;
CREATE TABLE TEMP (
    ID NUMBER(2) CONSTRAINTS temp_id_uq UNIQUE,
    NAME VARCHAR2(20),
    CITY VARCHAR2(20),
    CONSTRAINTS temp_name_uq UNIQUE(NAME)
);
--[2] ADD CONSTRAINTS WHEN TABLE IS AFTER CREATE TABLE

ALTER TABLE TEMP
    ADD CONSTRAINT temp_city_uq UNIQUE(CITY);

--[3] REMOVE OR DEROP CONSTRAINTS

ALTER TABLE TEMP 
	DROP CONSTRAINTS temp_city_uq;

--==============PRIMARY KEY CONSTRAINTS ============

--[1] ADD CONSTRAINTS WHEN TABLE IS CREATE

DROP TABLE TEMP;
CREATE TABLE TEMP (
	ID NUMBER(2) CONSTRAINT temp_id_pk PRIMARY KEY,
    NAME VARCHAR2(20),
    CITY VARCHAR2(20)
);
--NOTE
    --> COMPOSITE PRIMERY KEY
    --CONSTRAINTS temp_pk PRIMARY KEY(ID,NAME,CITY)

--[3] REMOVE OR DEROP CONSTRAINTS

ALTER TABLE TEMP 
	DROP CONSTRAINTS temp_id_pk;


--[2] ADD CONSTRAINTS WHEN TABLE IS AFTER CREATE TABLE

ALTER TABLE TEMP
    ADD CONSTRAINT temp_id_pk PRIMARY KEY(ID);


--==============CHECK CONSTRAINTS ============

--[1] ADD CONSTRAINTS WHEN TABLE IS CREATE

DROP TABLE TEMP;
CREATE TABLE TEMP (
	ID NUMBER(2) CONSTRAINT temp_id_ck CHECK(ID > 5),
    NAME VARCHAR2(20),
    CITY VARCHAR2(20)
);

--[2] ADD CONSTRAINTS WHEN TABLE IS AFTER CREATE TABLE

ALTER TABLE TEMP
    ADD CONSTRAINT temp_city_ck CHECK(CITY IN('MHV','BVN','SRT','RKT'));


--[3] REMOVE OR DEROP CONSTRAINTS
ALTER TABLE TEMP 
	DROP CONSTRAINTS temp_city_ck;




--==============FOREING KEY CONSTRAINTS ============

--[1] ADD CONSTRAINTS WHEN TABLE IS CREATE
DROP TABLE CHILD;
DROP TABLE PARENT;
CREATE TABLE PARENT (
	ID NUMBER(2),
    NAME VARCHAR2(20),
    CONSTRAINT parent_pk PRIMARY KEY(ID)
);
CREATE TABLE CHILD (
	ID NUMBER(2),
    PNAME VARCHAR2(20),
    PID NUMBER(2),
    CONSTRAINTS child_pid_fk FOREIGN KEY(PID) REFERENCES PARENT(ID)    
);

--[2] ADD CONSTRAINTS WHEN TABLE IS AFTER CREATE TABLE

ALTER TABLE CHILD
    ADD CONSTRAINTS child_pid_fk FOREIGN KEY(PID) REFERENCES PARENT(ID);             
--[3] REMOVE OR DEROP CONSTRAINTS

ALTER TABLE CHILD
    DROP CONSTRAINTS child_pid_fk;
